"use client"

import Head from "next/head"
import Button from "@mui/material/Button"
import { RiPlantFill } from "react-icons/ri/"

import React from "react"

export default function Home() {
  return (
    <>
      <Head>
        <title>CSF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-0">
        <div
          className="pt-32 bg-cover bg-center px-0 lg:px-0 bg-black"
          style={{ backgroundImage: `url("/images/img1.webp")` }}
        >
          <div className="flex mx-auto px-4 items-center border-b-8 border-black">
            <div className="flex flex-col lg:flex-row w-full items-center justify-between text-white pt-16 lg:pt-48 pb-10 px-4 lg:px-10 lg:pb-40 gap-10 lg:gap-0">
              <h1 className="text-2xl lg:text-4xl font-light text-left mb-0 pt-0 lg:w-1/2">
                A{" "}
                <span className="font-bold">
                  Calculadora de Impactos do Desmatamento
                </span>{" "}
                é uma ferramenta de valoração dos danos sociais e ambientais
                causados pelo desmatamento na Amazônia
              </h1>
              <div className="flex flex-col md:flex-row mx-auto gap-8">
                <Button
                  sx={{
                    backgroundColor: "#4ade80",
                    "&:hover": {
                      backgroundColor: "#dcfce7",
                    },
                    padding: "16px 32px",
                    color: "#052e16",
                    fontWeight: "normal",
                  }}
                  variant="contained"
                  color="primary"
                  size="large"
                  href="/guias-de-uso"
                  target="_self"
                >
                  GUIA DE USO
                </Button>
                <Button
                  sx={{
                    backgroundColor: "#4ade80",
                    "&:hover": {
                      backgroundColor: "#dcfce7",
                    },
                    padding: "16px 32px",
                    color: "#052e16",
                    fontWeight: "normal",
                  }}
                  variant="contained"
                  color="primary"
                  size="large"
                  href="/calculadora"
                  target="_self"
                >
                  CALCULADORA
                </Button>
              </div>
            </div>
          </div>
        </div>

        <h1 className="flex text-2xl md:text-2xl font-bold p-10 border-b-8 border-black gap-4 items-center">
          <RiPlantFill />
          Funções da Calculadora
        </h1>

        <div className="flex flex-col md:flex-row mx-0 md:mx-auto pt-0 justify-between items-center gap-10 md:gap-0">
          <div className="w-full md:w-1/2 p-10 md:border-r-8 border-black">
            <div className="mb-4 prose prose-lg leading-normal">
              <p>
                A Calculadora de Impactos do Desmatamento pode ser utilizada
                para três finalidades principais:
              </p>
              <div className="">
                <ul className="flex flex-col pl-4 border-l-0 border-black">
                  <li className="mb-0 font-bold">
                    Estimar valores de danos ambientais para apoiar a
                    definição de compensações e indenizações;
                  </li>
                  <li className="mb-0 font-bold">
                    Estimar níveis eficientes de investimentos para
                    planejamento e prevenção de impactos;
                  </li>
                  <li className="mb-0 font-bold">
                    Estimar receitas potenciais que o Estado poderia ter com
                    seus ativos florestais.
                  </li>
                </ul>
              </div>

              <p className="mt-4">
                Caso não tenha informações específicas, não tem problema, serão
                incluídos automaticamente valores médios de contexto e impacto e
                resultados e suas explicações serão gerados na sequencia.
              </p>
            </div>
          </div>

          <div
            className="bg-cover bg-center w-full md:w-1/2 h-[408px] border border-black bg-black"
            //style={{ backgroundImage: `url("/images/teste2.png")` }}
          >
            video
          </div>
        </div>

        <h1 className="flex text-2xl md:text-2xl font-bold p-10 border-t-8 border-black gap-4 items-center">
          <RiPlantFill /> Entenda os impactos do desmatamento
        </h1>

        <div className="mt-0 pt-0 pb-0 px-4 lg:px-0 border-y-8 border-black">
          <div className="mx-auto p-0">
            <div className="flex flex-col lg:flex-row justify-between p-0 gap-0">
              <div className="flex flex-col justify-start bg-white border-b-4 lg:border-b-0 pb-6 lg:pb-0 gap-4 shadow-none lg:w-1/2 lg:border-r-0 border-black">
                <div>
                  <img className="h-32 mx-auto pt-8" src="/images/ico1.svg" />
                  <div className="w-1/2 lg:w-2/3 mx-auto text-2xl xl:text-3xl font-bold mt-0 border-b-2 border-black px-4 py-4 text-center">
                    Restauração
                  </div>
                </div>
                <div className="text-left px-6 mx-auto prose prose-lg mt-4">
                  Refere-se aos gastos de implementação dos métodos
                  necessários para restaurar o meio ambiente e promover o
                  bem-estar humano que foi afetado. O custo de restauração é
                  aplicado sempre que o desmatamento é ilegal.
                </div>
              </div>

              <div className="flex flex-col justify-start bg-white border-0 p-0 gap-4 shadow-none lg:w-1/2 lg:border-l-8 border-black">
                <div>
                  <img className="h-32 mx-auto pt-8" src="/images/ico2.svg" />
                  <div className="w-1/2 lg:w-2/3 mx-auto text-2xl xl:text-3xl font-bold mt-0 border-b-2 border-black px-4 py-4 text-center">
                    Serviços Ecossistêmicos
                  </div>
                </div>
                <div className="text-left px-6 mx-auto prose prose-lg mt-4 mb-8">
                O desmatamento resulta na perda de benefícios econômicos e 
                não econômicos. Estas perdas são calculadas considerando 
                as alternativas de uso da terra. O custo de oportunidade 
                do desmatamento abrange a perda de recursos madeireiros e 
                não madeireiros, bem como serviços culturais e recreativos
                 que não têm preço de mercado direto. O desmatamento afeta
                 serviços ecossistêmicos essenciais, 
                 como sequestro de carbono e regulação da água, 
                 impactando o bem-estar da sociedade.
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
